<h2 class="text-center"><span class="glyphicon glyphicon-list"></span> Comments</h2>
<table class="table table-striped">
  <thead>
    <th class="col-md-2">Title</th>
    <th class="col-md-6">Description</th>
    <th class="col-md-2">Date</th>
    <th class="col-md-2">Ações</th>
  </thead>
  <tbody>
    <?php foreach($posts as $p):?>
      <tr>
        <td><?php echo $p->title; ?></td>
        <td><?php echo $p->description; ?></td>
        <td><?php echo $p->post_date; ?></td>
        <td><a href="/post/save/<?php echo $p->id; ?>" class="btn btn-warning"><span class="glyphicon glyphicon-edit"></span></a>
        <a href="/post/delete/<?php echo $p->id; ?>" class="btn btn-danger" rel="confirmation" title="Deseja excluir este registro?"><span class="glyphicon glyphicon-trash"></span></a></td>
      </tr>
      <?php endforeach;?>
  </tbody>
</table>

