<h2 class="text-center"><span class="glyphicon glyphicon-user"></span> <?php echo $this->translate('Users'); ?> </h2>
  <a class="btn btn-success pull-right" href="/user/save"><span class="glyphicon glyphicon-plus"></span> User </a>
<table class="table table-striped">
  <thead>
    <th class="col-md-2"><?php echo $this->translate('Username'); ?></th>
    <th class="col-md-2"><?php echo $this->translate('Name');?></th>
    <th class="col-md-2"><?php echo $this->translate('Valid');?></th>
    <th class="col-md-2"><?php echo $this->translate('Role');?></th>
    <th class="col-md-2"><?php echo $this->translate('Actions');?></th>
  </thead>
  <tbody>
    <?php foreach($users as $u): ?>
      <tr>
        <td><?php echo $u['username']; ?></td>
        <td><?php echo $u['name']; ?></td>
        <td><?php echo $u['valid'] ? $this->translate('Yes') : $this->translate('No') ; ?></td>
        <td><?php echo $u['role']; ?></td>
        <td><a href="/user/save/<?php echo $u['id'];; ?>" class="btn btn-warning"><span class="glyphicon glyphicon-edit"></span></a>
        <a href="/user/delete/<?php echo $u['id'];; ?>" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a></td>
      </tr>
      <?php endforeach;?>
  </tbody>
</table>
<div class="text-center">
  <?php
  echo $this->paginationControl(
    $users,
    'Sliding',
    'partials/paginator/control.phtml'
  );
  ?>
</div>
